name: apt-transport-oci

on:
  push:
    tags:
      - 'v*'

jobs:
  compile:
    name: Go OCI
    runs-on: ubuntu-latest
    steps:
      - name: Gooo
        uses: actions/setup-go@v2
        with:
          go-version: '1.9.3'
      - name: Check out the repo
        uses: actions/checkout@v2
          run: sudo go build -o /usr/lib/apt/methods/oci ./cmd/usr-lib-apt-methods-oci
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: /usr/lib/apt/methods/oci
