name: apt-transport-oci
on:
  push:
    tags:
      - 'v*'
jobs:
  make-image:
    runs-on: ubuntu-latest
    name: apt-oci-builder
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.9.3'
        run: |
              sudo go build -o /usr/lib/apt/methods/oci ./cmd/usr-lib-apt-methods-oci
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: /usr/lib/apt/methods/oci
