name: apt-transport-oci

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        uses: actions/setup-go@v2
        with:
          go-version: '1.9.3'
        run: |
            sudo go build -o /usr/lib/apt/methods/oci ./cmd/usr-lib-apt-methods-oci
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: /usr/lib/apt/methods/oci
